### ISSUE TITLE
Book rating

### ISSUE THREAD

**Issue by teodorszeltins** [latcraft/cloudopoly-search#6]
I have a feeling something is off with the rating system. 

The test tool says best book for "Linux" keyword is "Practical Vim" yet it seems it doesn't even have 15 votes. "Linux-Server mit Debian GNU/Linux: Das umfassende Praxis-Handbuch" has a solid 5 rating and 17 votes.

Also, what happens if two books have identical rating? Which comes first?

**Comment by aadamovich** [comment]
The rating of some books have changed since last updates of README. So, "Linux" book for "Ubuntu" keyword is the correct answer right now.

**Comment by Teodors** [comment]
Oh, cool. Thanks!
