### ISSUE TITLE
How to format book titles?

### ISSUE THREAD

**Issue by teodorszeltins** [latcraft/cloudopoly-search#7]
It seems all book titles are having a formating. This is very confusing. There is nothing written about it in the README. 

Should everything after colon be dropped? Should brackets also be dropped? What to do with  "OS X Lion - Einfach, wirkungsvoll und effizient nutzen". Should everything after dash also be dropped?

If we trim something down there might be books that collide and make errors, like "Linux: Das umfassende Handbuch (inkl. E-Book) (Galileo Computing)" and "Linux - Studentenausgabe (mit drei DVDs: Fedora 10, openSUSE 11.1 und Ubuntu 8.10)".

**Comment by jsaveljevs** [comment]
How should we handle collisions? E.g. there are "Mac OS X Snow Leopard: The Missing Manual" and "Mac OS X Snow Leopard: The Definitive Guide (Galileo Design)" books on DE site (http://www.amazon.de/s?url=search-alias%3Dstripbooks&field-keywords=MacOs&sort=review-rank). Those are not the same books, ISBN num is different.

**Comment by aadamovich** [comment]
Yes, according to the rules defined in the README we assume that "Mac OS X Snow Leopard: The Missing Manual" and "Mac OS X Snow Leopard: The Definitive Guide (Galileo Design)" is the same book, because their titles are the same after everything after colon or semicolon removed.
